# fly.toml file generated for hms-api on 2022-12-08T15:46:39+07:00

app = "hms-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"
  DB_USERNAME = "root"
  DB_PASSWORD = "password"
  DB_NAME = "db_hms"
  DB_ADDRESS = "mysql-hms.internal"
  DB_PORT = "3306"
  JWT_SECRET_KEY = "hms-16-backend jagoo huahuahua"
  APP_MODE = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
