name: CI HMS
on:
  pull_request:
    branches:
      - "master"
      - "development"
  push:
    branches:
      - "master"
      - "development"
jobs:
  unit-testing:
    name: "Testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: run unit test
        run: go test -v ./...
      - name: run linting
        uses: golangci/golangci-lint-action@v3